#!/usr/bin/env bash
# scripts/build_toc.sh — regenerate a SPEC's Table of contents.
#
# Usage:
#   build_toc.sh                       # rewrite the SPEC TOC in place
#   build_toc.sh --check               # exit 1 if the TOC is out of sync; no rewrite
#   build_toc.sh --spec <path> [...]   # operate on <path> instead of the default SPEC
#
# Default SPEC is the shell's own SPEC.md (self-located via this script's dir),
# so existing callers (`build_toc.sh`, `build_toc.sh --check`) are unchanged.
# `--spec <path>` (or `--spec=<path>`) points the same logic at a target's SPEC —
# this is how the shipped `check-toc.yml` validates a target's SPEC ToC (SPEC §1.3,
# #347). Arguments may appear in any order.
#
# The TOC lives between the markers:
#   <!-- TOC START — generated by scripts/build_toc.sh; do not edit by hand -->
#   <!-- TOC END -->
#
# It enumerates every heading at depth 2-4 whose first token is a section
# number (e.g. `## 0. Intent and scope`, `### 1.4 PR-as-living-doc`,
# `#### 5.7.1 Operating modes …`). Each row shows the section id, the
# title, and the line number — enabling targeted Read --offset --limit.

set -uo pipefail

SHELL_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
SPEC="$SHELL_ROOT/SPEC.md"   # default: the shell's own SPEC (unchanged)
MODE="write"

while [ $# -gt 0 ]; do
  case "$1" in
    --check)    MODE="--check" ;;
    write)      MODE="write" ;;
    --spec)     shift; SPEC="${1:?build_toc: --spec requires a path}" ;;
    --spec=*)   SPEC="${1#--spec=}" ;;
    *) echo "build_toc: unknown argument: $1" >&2; exit 2 ;;
  esac
  shift
done

if [ ! -f "$SPEC" ]; then
  echo "build_toc: SPEC not found at $SPEC" >&2
  exit 2
fi

TOC_START='<!-- TOC START — generated by scripts/build_toc.sh; do not edit by hand -->'
TOC_END='<!-- TOC END -->'

# awk program — single source of truth for heading→TOC-row formatting.
# Filters depth-2/3/4 headings whose first token matches a section-number
# pattern (digits with optional dots), emits a markdown table row with
# &nbsp; indentation, the § sigil, the title, and the line number.
AWK_PROG='
  /^#{2,4} [0-9]/ {
    n = 0
    while (substr($0, n + 1, 1) == "#") n++
    rest = substr($0, n + 2)
    sp = index(rest, " ")
    if (sp == 0) next
    id = substr(rest, 1, sp - 1)
    title = substr(rest, sp + 1)
    sub(/\.$/, "", id)
    if (id !~ /^[0-9]+(\.[0-9]+)*$/) next
    indent = ""
    for (i = 0; i < n - 2; i++) indent = indent "&nbsp;&nbsp;"
    printf("| %s\xc2\xa7%s | %s | %d |\n", indent, id, title, NR)
  }
'

# render_toc_into <output_path>
#   Reads $SPEC, builds the TOC block, writes the full SPEC contents with
#   the new TOC spliced in, to <output_path>.
render_toc_into() {
  local out="$1"
  local start_ln end_ln new_body new_block
  start_ln=$(grep -nF "$TOC_START" "$SPEC" | head -1 | cut -d: -f1)
  if [ -z "$start_ln" ]; then
    echo "build_toc: TOC START marker not found in SPEC.md" >&2
    return 2
  fi
  # Pin end_ln to the first END marker STRICTLY AFTER start_ln so prose
  # mentions of the markers don't false-match.
  end_ln=$(awk -v start="$start_ln" -v needle="$TOC_END" '
    NR > start && index($0, needle) { print NR; exit }
  ' "$SPEC")
  if [ -z "$end_ln" ]; then
    echo "build_toc: TOC END marker not found after TOC START in SPEC.md" >&2
    return 2
  fi

  new_body=$(awk "$AWK_PROG" "$SPEC")
  if [ -z "$new_body" ]; then
    echo "build_toc: no numbered headings found in SPEC.md" >&2
    return 2
  fi
  new_block="$TOC_START
| Section | Title | Line |
|---|---|---|
$new_body
$TOC_END"

  {
    head -n $((start_ln - 1)) "$SPEC"
    printf '%s\n' "$new_block"
    tail -n +$((end_ln + 1)) "$SPEC"
  } > "$out"
}

# --check mode: render to a temp file, compare, never write to SPEC.
if [ "$MODE" = "--check" ]; then
  tmp=$(mktemp)
  trap 'rm -f "$tmp"' EXIT
  render_toc_into "$tmp" || exit $?
  if cmp -s "$SPEC" "$tmp"; then
    exit 0
  fi
  echo "build_toc: SPEC.md TOC is out of sync." >&2
  echo "build_toc: run scripts/build_toc.sh to regenerate." >&2
  exit 1
fi

# write mode: iterate to fixed point. The first pass uses line numbers
# from the *input* file; replacing the TOC block shifts every numbered
# heading by the size delta. The second pass reads the new file and
# emits correct line numbers. Heading count is invariant across passes,
# so the TOC SIZE is stable from pass 2 onward — fixed-point in ≤2
# iterations. The bound `2` here is a safety cap, not an optimization.
for pass in 1 2 3; do
  tmp=$(mktemp)
  render_toc_into "$tmp" || { rm -f "$tmp"; exit $?; }
  if cmp -s "$SPEC" "$tmp"; then
    rm -f "$tmp"
    echo "build_toc: SPEC.md TOC up to date (converged in pass $pass)."
    exit 0
  fi
  mv "$tmp" "$SPEC"
done

# If we reach here, the TOC didn't converge in 3 passes — should be impossible
# given heading-count invariance. Surface it loudly rather than loop forever.
echo "build_toc: TOC failed to converge after 3 passes — check for marker corruption" >&2
exit 2
